discovery:
  strategy:
    selection: random
    prediction: static
  address:
    service-discovery: >
      http://34.90.202.154:8761
    service-monitoring: http://34.90.202.154:8763
    ml-engine: >
      http://localhost:8764
  scheduler.cron:
    registry: 60000      # 60 seconds
    monitoring: 30000    # 30 seconds
    training: 86400000   # 24 hours
